### ISSUE TITLE
Error: "unexpected keyword argument 'hyperparameters_randomtune" and how to load initial matrix

### ISSUE THREAD

**Issue by robliou** [mcmahon-lab/cim-optimizer#1]
Hello! I am attempting to use cim-optimizer to see if I can simulate a CIM to solve a few Max-Cut problems of different sizes (i.e. vertices =5, 25, 100, etc.). The matrices I'm testing are in the format given below:

matrix = -np.array([
                [0, 1, 0, 1, 1, 0],
                [1, 0, 1, 0, 0, 1],
                [0, 1, 0, 1, 1, 0],
                [1, 0, 1, 0, 0, 1],
                [1, 0, 1, 0, 0, 1],
                [0, 1, 0, 1, 1, 0],       
            ])

My first question is, how do I properly load this matrix into the Jupyter Notebook using the given line: 
```J = - np.load(instance_path_str_MAXCUT + f"MC50_N={N}_{mc_id}.npz")["arr_0"]```?

Secondly, I find that replacing 'J' in the formulas with the variable 'matrix' above appears to somewhat work (though I can't seem to find the ground_energy_state using this method). 

However, when I run the following line:

``test = Ising(matrix).solve(cac_gamma=gamma, hyperparameters_randomtune = False)``

I get the error:

``TypeError: Ising.solver.__init__() got an unexpected keyword argument 'hyperparameters_randomtune'``

Removing the parameter 'hyperparameters_randomtune=False' allows the code to run, but at this point, I'm not sure if I'm still running the program properly..

Can you please assist with these two initial questions?

Thanks,

Rob

**Comment by robliou** [comment]
As a follow-up here, I was able to address the ```unexpected keyword argument 'hyperparameters_randomtune'``` issue by simply downloading the files to my local computer, manually editing the parameter to ```False``` in the ```class solver``` in the ```solve_Ising.py``` file, and then running locally. Issue seems to disappear this way.

As for loading the initial matrix, simply pasting the matrix into the code (and thus bypassing the load method) appears to work just fine.

As such, please feel free to close these issues as well. 

Thanks,

**Comment by tylertking** [comment]
Thank you for your interest in our repository! This issue was caused by an out-of-date PyPI version that I didn't notice beforehand. I'm really sorry about the confusion, and I've updated the [PyPI version](https://pypi.org/project/cim-optimizer/1.0.4/) to accurately reflect our recent changes in commit [35f23c9](https://github.com/mcmahon-lab/cim-optimizer/commit/35f23c9269490e890c6d0c3529f951cef2e64632).

Again I'm really sorry about this issue, and I'm glad you were able to work by loading the code locally. If anything else comes up feel free to reopen the issue and/or opening another issue.
